package com.opencassandra;

import java.sql.SQLException;
import java.util.ArrayList;

public class Testy {
//	String sql = "delete from speed_test_new_"+month+" where delay is NULL and max_up is null and max_down is null ; ";
////	list.add(sql);
//	sql = "DELETE a FROM  speed_test_new_"+month+" a where EXISTS (select * from speed_test_"+month+"  b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "update speed_test_new_"+month+" set normalornot =  (case when signal_strength = '' or signal_strength is null or avg_up=0  THEN 'no'  else 'yes'  end) ";
//	list.add(sql);
//	sql = "DELETE a from  ping_new_"+month+" a where EXISTS (select * from ping_"+month+" b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "update ping_new_"+month+" set normalornot = (case when(signal_strength = '' or signal_strength is null) or (max_rtt is not null and min_rtt is not null and avg_rtt is not null and success_rate = '0') or success_rate='--'  then 'no' else 'yes' end)";
//	list.add(sql);
//	sql = "DELETE a from  ping_new_"+month+" a where EXISTS (select * from ping_"+month+" b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "DELETE a from  http_test_new_"+month+" a where EXISTS (select * from http_test_"+month+"  b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "update http_test_new_"+month+" set resource_size = SUBSTRING_INDEX(SUBSTRING_INDEX(resource_size, '/', -1),'M',1)";
//	list.add(sql);
//	sql = "update http_test_new_"+month+" set avg_rate = avg_rate/1024, max_rate = max_rate/1024  WHERE  avg_rate>100  and  max_rate>100 ";
//	list.add(sql);
//	sql = "update http_test_new_"+month+" set normalornot = (case when signal_strength = '' or signal_strength is null or avg_rate>100  THEN 'no'  else 'yes'  end)";
//	list.add(sql);
//	sql = "delete from http_test_new_"+month+" where file_type is null;";
//	list.add(sql);
//	sql = "update web_browsing_new_"+month+" set normalornot = (case when (signal_strength = '' or signal_strength is null) or (reference=0 and success_rate = '100')  THEN 'no' else 'yes' end)";
//	list.add(sql);
//	sql = "DELETE a from web_browsing_new_"+month+" a where EXISTS (select * from web_browsing_"+month+"  b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "DELETE a from  hand_over_new_"+month+" a where EXISTS (select * from hand_over_"+month+" b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "update hand_over_new_"+month+" set normalornot = (case when signal_strength = '' or signal_strength is null  THEN 'no'   else 'yes'   end)";
//	list.add(sql);
//	sql = "DELETE a from  call_test_new_"+month+" a where EXISTS (select * from call_test_"+month+" b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "update call_test_new_"+month+" set normalornot = (case when signal_strength = '' or signal_strength is null  THEN 'no'  else 'yes'  end)";
//	list.add(sql);
//	sql = "DELETE a from  sms_new_"+month+" a where EXISTS (select * from sms_"+month+" b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "update sms_new_"+month+" set normalornot = (case when (signal_strength = '' or signal_strength is null) or (sending_delay = NULL and success_rate='100')  then 'no'  else 'yes'  end)";
//	list.add(sql);
//	sql = "DELETE a from  video_test_new_"+month+" a where EXISTS (select * from video_test_"+month+" b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "DELETE a from  sms_query_new_"+month+" a where EXISTS (select * from sms_query_"+month+" b where b.id=a.id and b.haschange=0);";
//	list.add(sql);
//	sql = "update sms_query_new_"+month+" set  normalornot = (case when (signal_strength = '' or signal_strength is null) or (sending_delay=0 and success_rate='100%')  then 'no'  else 'yes'  end)";
//	list.add(sql);
//	sql = "update speed_test_"+month+" a set a.haschange =1 where a.haschange=0 and  EXISTS (select * from speed_test_new_"+month+" b where a.id=b.id );";
//	list.add(sql);
//	sql = "update ping_"+month+" a  set  a.haschange =1 where a.haschange=0 and EXISTS (select *  from ping_new_"+month+"  b where  a.id=b.id ) ;";
//	list.add(sql);
//	sql = "update http_test_"+month+" a  set  a.haschange =1 where a.haschange=0  and EXISTS (select *  from http_test_new_"+month+"  b where  a.id=b.id ) ;";
//	list.add(sql);
//	sql = "update web_browsing_"+month+" a  set a.haschange =1 where a.haschange=0 and EXISTS (select *  from web_browsing_new_"+month+"  b where a.id=b.id) ;";
//	list.add(sql);
//	sql = "update hand_over_"+month+" a  set a.haschange =1 where a.haschange=0 and EXISTS (select *  from hand_over_new_"+month+"  b where a.id=b.id) ;";
//	list.add(sql);
//	sql = "update call_test_"+month+" a  set a.haschange =1 where a.haschange=0 and EXISTS (select *  from call_test_new_"+month+"  b where a.id=b.id) ;";
//	list.add(sql);
//	sql = "update sms_"+month+" a  set  a.haschange =1 where a.haschange=0 and EXISTS (select *  from sms_new_"+month+"  b where  a.id=b.id ) ;";
//	list.add(sql);
//	sql = "update video_test_"+month+" a  set  a.haschange =1 where a.haschange=0 and EXISTS (select *  from video_test_new_"+month+"  b where  a.id=b.id ) ;";
}
